# -*- coding: utf-8 -*-

{
    'name': 'Kənd Təsərrüfatı İdarəetmə Sistemi',
    'version': '18.0.1.1.0',
    'category': 'Agriculture',
    'website': 'https://www.github.com/7aim',
    'depends': ['base', 'stock', 'product','purchase'],
    'data': [
        'security/ir.model.access.csv',
        'data/farm_data.xml',
        #'data/founder_demo_data.xml',
        'views/farm_field_wizard_views.xml',
        'views/farm_field_views.xml',
        'views/farm_parcel_views.xml',
        'views/farm_row_views.xml',
        'views/farm_tree_views.xml',
        'views/farm_variety_views.xml',
        'views/farm_disease_views.xml',
        'views/farm_pallet_views.xml',
        'views/farm_cooler_views.xml',
        'views/farm_operations_views.xml',
        'views/farm_worker_views.xml',
        'views/farm_expense_views.xml',
        'views/farm_cash_views.xml',
        'views/farm_expense_report_views.xml',
        'views/farm_communal_expense_views.xml',
        'views/farm_diesel_expense_views.xml',
        'views/farm_tractor_expense_views.xml',
        'views/farm_material_expense_views.xml',
        'views/farm_hotel_expense_views.xml',
        'views/product_template_views.xml',
        'views/farm_menu.xml',
        'views/purchase_order.xml',
    ],

    'installable': True,
    'auto_install': False,
    'application': True,
}