from . import farm_field
from . import farm_parcel
from . import farm_row
from . import farm_tree
from . import farm_variety
from . import farm_disease
from . import farm_pallet
from . import farm_cooler
from . import farm_operations
from . import farm_worker
from . import farm_meter
from . import farm_resource
from . import farm_document
from . import purchase_order
from . import farm_communal_expense
from . import farm_diesel_expense
from . import farm_tractor_expense
from . import farm_tractor_income
from . import farm_material_expense
from . import farm_hotel_expense
from . import farm_cash_flow
from . import farm_future_expense
from . import farm_expense_report
from . import product_template
from . import res_partner
from . import farm_dashboard_wizard
from . import farm_equipment